// Tes Spasial - 25 soal (text-based spatial reasoning)
module.exports = [
  { q: "Jika sebuah kubus diputar 90° ke kanan, sisi yang semula menghadap atas akan menghadap ke?", o: ["Bawah","Kanan","Depan","Belakang"], a: 1 },
  { q: "Cermin memantulkan huruf 'b'. Apa yang terlihat di cermin?", o: ["b","d","p","q"], a: 1 },
  { q: "Berapa banyak kubus kecil yang dibutuhkan untuk membuat kubus 3x3x3?", o: ["9","18","27","36"], a: 2 },
  { q: "Jika sebuah kertas persegi dilipat diagonal lalu dipotong ujungnya, berapa lubang saat dibuka?", o: ["1","2","3","4"], a: 0 },
  { q: "Bayangan cermin dari angka '8' adalah?", o: ["8","6","3","E"], a: 0 },
  { q: "Bangun datar yang memiliki 6 sisi sama panjang disebut?", o: ["Pentagon","Heksagon","Oktagon","Desagon"], a: 1 },
  { q: "Jika huruf 'R' diputar 180°, hasilnya menyerupai huruf apa?", o: ["R terbalik","P","d","Я"], a: 0 },
  { q: "Berapa sisi yang dimiliki oleh prisma segitiga?", o: ["3","4","5","6"], a: 2 },
  { q: "Sebuah kubus memiliki berapa rusuk?", o: ["6","8","10","12"], a: 3 },
  { q: "Jika sebuah persegi panjang dilipat menjadi dua bagian sama besar secara horizontal, bentuknya menjadi?", o: ["Segitiga","Persegi panjang lebih kecil","Trapesium","Jajar genjang"], a: 1 },
  { q: "Berapa banyak segitiga yang terbentuk jika menarik semua diagonal dari segi lima?", o: ["3","5","8","10"], a: 2 },
  { q: "Sebuah limas segi empat memiliki berapa titik sudut?", o: ["4","5","6","8"], a: 1 },
  { q: "Jika Anda berdiri menghadap utara lalu berputar 270° searah jarum jam, Anda menghadap ke?", o: ["Utara","Timur","Selatan","Barat"], a: 1 },
  { q: "Bayangan cermin dari kata 'KODE' dibaca menjadi?", o: ["EDOK","KOBE","3DOK","KODE"], a: 0 },
  { q: "Benda 3D yang memiliki 2 lingkaran sebagai alas dan tutup adalah?", o: ["Kerucut","Tabung","Bola","Prisma"], a: 1 },
  { q: "Berapa jumlah sisi pada balok?", o: ["4","6","8","12"], a: 1 },
  { q: "Jika kubus dilihat dari sudut atas, tampilannya adalah?", o: ["Lingkaran","Persegi","Segitiga","Belah ketupat"], a: 1 },
  { q: "Jaring-jaring kubus memiliki berapa persegi?", o: ["4","5","6","8"], a: 2 },
  { q: "Sebuah kerucut diiris horizontal di tengah, irisan yang terbentuk berbentuk?", o: ["Segitiga","Lingkaran","Persegi","Elips"], a: 1 },
  { q: "Dari 8 titik sudut kubus, berapa diagonal ruang yang bisa dibuat?", o: ["2","4","6","8"], a: 1 },
  { q: "Jika Anda berjalan 5 langkah ke utara, 3 ke timur, 5 ke selatan, Anda berada di sebelah mana dari titik awal?", o: ["Utara","Timur","Selatan","Barat"], a: 1 },
  { q: "Bangun ruang yang semua sisinya berbentuk segitiga sama sisi (4 sisi) disebut?", o: ["Kubus","Tetrahedron","Oktahedron","Ikosahedron"], a: 1 },
  { q: "Berapa banyak simetri putar yang dimiliki persegi?", o: ["1","2","4","8"], a: 2 },
  { q: "Jika silinder dipotong vertikal tepat di tengah, bentuk potongannya?", o: ["Lingkaran","Persegi panjang","Elips","Segitiga"], a: 1 },
  { q: "Sebuah bola diiris oleh sebuah bidang datar, bentuk irisannya adalah?", o: ["Persegi","Segitiga","Lingkaran","Elips"], a: 2 },
];
